name: MaggieMar
favicon: null
layout_spectrum: 0.5737264277413487
typography_spectrum: 0.22430019662715495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#170F0E'
    - '#290418'
    - '#505217'
    - '#FFD372'
    - '#FFF1AF'
  brandStrength: 0.087447116849944
  lightness: 0.47620696807280183
  saturation: 0.8431493723765016
  rhythmicContrast: 0.9388665456790477
purpose: []
